# Generated by Django 5.1.3 on 2024-11-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Channel Name')),
                ('chat_id', models.CharField(max_length=50, unique=True, verbose_name='Channel ID')),
                ('channels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.channels')),
            ],
        ),
    ]
